# Generated by Django 4.2.7 on 2025-11-02 16:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diagnostic', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Diagnostics',
                'ordering': ['-date_diagnostic'],
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etablissement', models.CharField(max_length=200)),
                ('adresse_etablissement', models.TextField()),
                ('type_etablissement', models.CharField(choices=[('hopital', 'Hôpital'), ('clinique', 'Clinique'), ('cabinet', 'Cabinet Médical'), ('pharmacie', 'Pharmacie'), ('laboratoire', 'Laboratoire')], default='hopital', max_length=20)),
                ('capacite', models.IntegerField(default=0)),
                ('certifications', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Établissements',
            },
        ),
        migrations.CreateModel(
            name='ImpactEnvironnemental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_impact', models.CharField(choices=[('faible', 'Impact Faible'), ('modere', 'Impact Modéré'), ('eleve', 'Impact Élevé')], max_length=20)),
                ('score_carbone', models.DecimalField(decimal_places=2, help_text='Score en kg CO2', max_digits=10)),
                ('consommation_eau', models.DecimalField(decimal_places=2, help_text='Consommation en litres', max_digits=10)),
                ('dechets', models.DecimalField(decimal_places=2, help_text='Déchets en kg', max_digits=10)),
                ('recyclable', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Impact Environnemental',
                'verbose_name_plural': 'Impacts Environnementaux',
            },
        ),
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_maladie', models.CharField(max_length=200, unique=True)),
                ('code_cim10', models.CharField(blank=True, max_length=10)),
                ('type_maladie', models.CharField(choices=[('chronique', 'Maladie Chronique'), ('aigue', 'Maladie Aiguë'), ('infectieuse', 'Maladie Infectieuse'), ('cardiovasculaire', 'Maladie Cardiovasculaire'), ('respiratoire', 'Maladie Respiratoire')], max_length=30)),
                ('gravite', models.CharField(choices=[('legere', 'Légère'), ('moderee', 'Modérée'), ('grave', 'Grave')], max_length=20)),
                ('taux_mortalite', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('contagieuse', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Maladies',
            },
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_medicament', models.CharField(max_length=200, unique=True)),
                ('type_medicament', models.CharField(choices=[('antibiotique', 'Antibiotique'), ('anti_inflammatoire', 'Anti-inflammatoire'), ('analgesique', 'Analgésique'), ('antiviral', 'Antiviral'), ('anticoagulant', 'Anticoagulant')], max_length=30)),
                ('dosage', models.CharField(max_length=100)),
                ('forme', models.CharField(help_text='Comprimé, sirop, injection, etc.', max_length=50)),
                ('fabricant', models.CharField(max_length=200)),
                ('effets_secondaires', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Médicaments',
            },
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_traitement', models.CharField(max_length=200)),
                ('type_traitement', models.CharField(choices=[('medicamenteux', 'Traitement Médicamenteux'), ('chirurgie', 'Chirurgie'), ('physiotherapie', 'Physiothérapie'), ('radiotherapie', 'Radiothérapie'), ('psychotherapie', 'Psychothérapie')], max_length=30)),
                ('cout', models.DecimalField(decimal_places=2, help_text='Coût en euros', max_digits=10)),
                ('duree', models.IntegerField(help_text='Durée en jours')),
                ('efficacite', models.DecimalField(decimal_places=2, help_text='Efficacité en %', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('impact_environnemental', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traitement', to='ontology_app.impactenvironnemental')),
                ('maladie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='ontology_app.maladie')),
                ('medicaments', models.ManyToManyField(blank=True, related_name='traitements', to='ontology_app.medicament')),
            ],
            options={
                'verbose_name_plural': 'Traitements',
            },
        ),
        migrations.CreateModel(
            name='Symptome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_symptome', models.CharField(max_length=200)),
                ('type_symptome', models.CharField(choices=[('respiratoire', 'Symptôme Respiratoire'), ('digestif', 'Symptôme Digestif'), ('neurologique', 'Symptôme Neurologique'), ('douleur', 'Douleur'), ('fievre', 'Fièvre')], max_length=30)),
                ('intensite', models.CharField(choices=[('faible', 'Faible'), ('moderee', 'Modérée'), ('forte', 'Forte')], max_length=20)),
                ('duree_symptome', models.IntegerField(help_text='Durée en jours')),
                ('maladies', models.ManyToManyField(blank=True, related_name='symptomes', to='ontology_app.maladie')),
            ],
            options={
                'verbose_name_plural': 'Symptômes',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prescription', models.DateTimeField(auto_now_add=True)),
                ('posologie', models.TextField(help_text='Instructions de prise')),
                ('duree_prescription', models.IntegerField(help_text='Durée en jours')),
                ('renouvellement', models.BooleanField(default=False)),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='ontology_app.diagnostic')),
                ('traitement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='ontology_app.traitement')),
            ],
            options={
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-date_prescription'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], default='M', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_securite_sociale', models.CharField(max_length=15, unique=True)),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('groupe_sanguin', models.CharField(blank=True, max_length=5)),
                ('allergies', models.TextField(blank=True)),
                ('etablissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='ontology_app.etablissement')),
            ],
            options={
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], default='M', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_ordre', models.CharField(max_length=20, unique=True)),
                ('specialite', models.CharField(choices=[('generaliste', 'Généraliste'), ('cardiologue', 'Cardiologue'), ('pneumologue', 'Pneumologue'), ('autre', 'Autre spécialité')], max_length=50)),
                ('annees_experience', models.IntegerField(default=0)),
                ('etablissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medecins', to='ontology_app.etablissement')),
            ],
            options={
                'verbose_name_plural': 'Médecins',
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_examen', models.CharField(max_length=200)),
                ('type_examen', models.CharField(choices=[('biologique', 'Examen Biologique'), ('imagerie', "Examen d'Imagerie"), ('clinique', 'Examen Clinique'), ('fonctionnel', 'Examen Fonctionnel')], max_length=30)),
                ('date_examen', models.DateField()),
                ('resultat', models.TextField(blank=True)),
                ('cout_examen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maladies_diagnostiquees', models.ManyToManyField(blank=True, related_name='examens', to='ontology_app.maladie')),
            ],
            options={
                'verbose_name_plural': 'Examens',
            },
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='examens',
            field=models.ManyToManyField(blank=True, related_name='diagnostics', to='ontology_app.examen'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='maladie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='ontology_app.maladie'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='ontology_app.medecin'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='ontology_app.patient'),
        ),
    ]
